services:
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - "5432:5432"
  #   tmpfs:
  #     - /var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container

    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1"]
volumes:
  redis-data:
    driver: local